### ISSUE TITLE
Documentation build warnings/errors

### ISSUE THREAD

**Issue by simmsa** [MHKiT-Software/MHKiT#61]
Below is the current output from `make html` after running `make clean`:

```
make html
sphinx-build -b html -d ./doctrees   source .
Running Sphinx v7.2.6
WARNING: html_static_path entry '_static' is placed inside outdir
loading pickled environment... checking bibtex cache... up to date
done
[autosummary] generating autosummary for: ADCP_Delft3D_TRTS_example.ipynb, Delft3D_example.ipynb, PacWave_resource_characterization_example.ipynb, SWAN_example.ipynb, WPTO_hindcast_example.ipynb, adcp_example.ipynb, adv_example.ipynb, cdip_example.ipynb, citeus.rst, contact.rst, ..., short_term_extremes_example.ipynb, terminology.rst, tidal.rst, tidal_example.ipynb, troubleshooting.rst, utils.rst, wave.rst, wave_example.ipynb, webinars.rst, wecsim_example.ipynb
WARNING: [sphinxcontrib-matlabdomain] Unexpected class attribute: 'TestTags'.  In 'mhkit.tests.Loads_TestLoads'.
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 10 changed, 0 removed
reading sources... [100%] python
<repo location>/MHKiT/docs/source/ADCP_Delft3D_TRTS_example.ipynb:2181: ERROR: Unexpected indentation.
<repo location>/MHKiT/docs/source/ADCP_Delft3D_TRTS_example.ipynb:2178: WARNING: Inline interpreted text or phrase reference start-string without end-string.
<repo location>/MHKiT/docs/source/ADCP_Delft3D_TRTS_example.ipynb:2182: WARNING: Block quote ends without a blank line; unexpected unindent.
<repo location>/MHKiT/docs/source/ADCP_Delft3D_TRTS_example.ipynb:62: WARNING: image file not readable: data/river/ADCP_transect/TRTS_transect_map.png
<repo location>/MHKiT/docs/source/ADCP_Delft3D_TRTS_example.ipynb:62: WARNING: image file not readable: data/river/ADCP_transect/TRTS_transect_map.png
docstring of mhkit.qc.check_delta:30: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of mhkit.river.IO.request_usgs_data:20: ERROR: Unexpected indentation.
docstring of mhkit.river.IO.request_usgs_data:21: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of mhkit.tidal.io.request_noaa_data:17: ERROR: Unexpected indentation.
docstring of mhkit.tidal.io.request_noaa_data:18: WARNING: Block quote ends without a blank line; unexpected unindent.
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.power_coefficient:1: WARNING: duplicate object description of mhkit.river.performance.power_coefficient, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.tip_speed_ratio:1: WARNING: duplicate object description of mhkit.river.performance.tip_speed_ratio, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.circular:1: WARNING: duplicate object description of mhkit.river.performance.circular, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.rectangular:1: WARNING: duplicate object description of mhkit.river.performance.rectangular, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.multiple_circular:1: WARNING: duplicate object description of mhkit.river.performance.multiple_circular, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
<repo location>/MHKiT/MHKiT-MATLAB/mhkit/river/performance:docstring of mhkit.river.performance.ducted:1: WARNING: duplicate object description of mhkit.river.performance.ducted, other instance in <repo location>/MHKiT/docs/source/mhkit-matlab/api.river.rst, use :noindex: for one of them
docstring of mhkit.utils.magnitude_phase:7: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of mhkit.utils.magnitude_phase:14: ERROR: Unexpected indentation.
docstring of mhkit.wave.IO.hindcast.request_wpto:13: ERROR: Unexpected indentation.
docstring of mhkit.wave.IO.hindcast.request_wpto:15: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of mhkit.wave.IO.hindcast.request_wpto:28: CRITICAL: Unexpected section title.

Returns
-------
docstring of mhkit.wave.IO.NDBC.NDBC_request_data:17: ERROR: Unexpected indentation.
docstring of mhkit.wave.IO.NDBC.NDBC_request_data:18: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of mhkit.wave.IO.NDBC.NDBC_available_data:14: ERROR: Unexpected indentation.
docstring of mhkit.wave.IO.NDBC.NDBC_available_data:15: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of mhkit.wave.graphics.plot_chakrabarti:22: CRITICAL: Unexpected section title or transition.

--------
<repo location>/MHKiT/docs/source/mhkit-python/api.utils.rst:10: WARNING: autosummary: failed to import mhkit.utils.index_to_datetime.
Possible hints:
* AttributeError: module 'mhkit.utils' has no attribute 'index_to_datetime'
* ModuleNotFoundError: No module named 'mhkit.utils.index_to_datetime'
* ImportError:
WARNING: autodoc: failed to import function 'index_to_datetime' from module 'mhkit.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/util/inspect.py", line 330, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'mhkit.utils' has no attribute 'index_to_datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 135, in import_object
    obj = attrgetter(obj, mangled_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 319, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 2810, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/util/inspect.py", line 346, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: index_to_datetime

<repo location>/MHKiT/docs/source/python.rst:32: WARNING: toctree contains reference to nonexisting document 'tidal_performance_example'
<repo location>/MHKiT/docs/source/python.rst:32: WARNING: toctree contains reference to nonexisting document 'mooring_example'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] python
generating indices... genindex mat-modindex py-modindex done
copying linked files...
copying notebooks ... [100%] ADCP_Delft3D_TRTS_example.ipynb
highlighting module code... [100%] pecos.monitoring
writing additional pages... search done
copying images... [100%] figures/mathworks-logo-full-color-rgb.png
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 32 warnings.

The HTML pages are in ..

Build finished. The HTML pages are in .
```

There are multiple warnings/errors going on. This is a starting point for further investigation

**Comment by akeeste** [comment]
1 warnings remain (a TODO for automating the build/deploy actions). I repressed the docutils format warnings that don't seem to impact the API documentation building. Closing this as largely resolved by #80
